language: cpp
dist: bionic
jobs:
  include:
    - stage: Bare metal build
      before_install:
        - sudo apt update
        - sudo apt install cmake libboost-dev
      install:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release
      script:
        - make -j
    - stage: Dockerfile build
      services:
        - docker
      script:
        - docker build .
