language: cpp
dist: bionic
jobs:
  include:
    - addons:
        apt:
          packages:
            - libboost-dev
            - libgmp-dev
      install:
        - mkdir build
        - cd build
        - cmake ..
        - make -j3
      script:
        - cd ..
        - scripts/runperf.sh ebpf-samples zoneCrab
    - services: docker
      script: docker build .
