language: cpp
dist: bionic
jobs:
  include:
    - before_install:
        - sudo apt update
        - sudo apt install cmake libboost-dev
      install:
        - mkdir build
        - cd build
        - cmake ..
        - make -j3
      script:
        - cd ..
        - scripts/runperf.sh ebpf-samples zoneCrab
    - services: docker
      script: docker build .
