language: cpp
dist: bionic
jobs:
  include:
    - addons:
        apt:
          packages:
            - libboost-graph1.65-dev
            - libboost1.65-tools-dev
      install:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release
        - make -j3
      script:
        - cd ..
        - scripts/runperf.sh ebpf-samples zoneCrab
    - services: docker
      script: docker build .
